name: Gradle Distribute

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Verify Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Execute jlink
        run: ./gradlew jlink

      - name: Execute jpackage
        run: ./gradlew jpackage

      # Upload artefacts
      # macOS
      - name: Upload DMG as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: tile-mapper-${{ matrix.os }}-x64-dmg
          path: build/jpackage/*.dmg

      # Windows
      - name: Upload EXE as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: tile-mapper-${{ matrix.os }}-exe
          path: build/jpackage/*.exe

      - name: Upload MSI as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: hellofx-jdk${{ matrix.java }}-${{ matrix.os }}-msi
          path: build/jpackage/*.msi

      # Linux
      - name: Upload DEB as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: tile-mapper-${{ matrix.os }}-deb
          path: build/jpackage/*.deb

      - name: Upload RPM as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: tile-mapper-${{ matrix.os }}-rpm
          path: build/jpackage/*.rpm